### ISSUE TITLE
Function to backcalculate Rt and the growth rate

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#116]
As shown here: 

https://github.com/CDCgov/Rt-without-renewal/blob/0c03621be16aa66c4ada8ec7248dafeeee68cf0f/EpiAware/docs/src/examples/getting_started.jl#L331-L332

We need a function to backcalculate Rt and the growth rate from infections generated in an arbitrary model

**Comment by SamuelBrand1** [comment]
This is a good idea, but not really implementable in an _arbitrary model_. Do you mean one with a single infected type as per how we have been doing it?

**Comment by seabbs** [comment]
yes and I was thinking we would use it in the generated quantities return and make sure it only got called via multiple dispatch when it would work (would need to have some kind of function that it nested in though not sure what to call that given that generated_quantities is taken...) -> maybe `situtational_awareness_metrics()`?

**Comment by seabbs** [comment]
backcalculating Rt is handled in #184

**Comment by seabbs** [comment]
Is this complete? I don't think we have a function for the growth rate explicitly (though as it can wrap the Rt one perhaps we do)

**Comment by SamuelBrand1** [comment]
I'm doing this for the pipeline... which means avoiding dealing with multi-groups. Would that close this issue?

**Comment by seabbs** [comment]
Shall we just make a `expected_growth` or similar to match the current `expected_Rt` in EpiAware and use that?
