### ISSUE TITLE
Code organisation

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#125]
At what point should we reorganise our src folder? It seems like we could have a model per abstract type (so obs, latent etc) and a utilities module? Or is that too much? 

If we did that then it seems like having things in folders by module might be nice? It seems like its a bit all over the place currently.

**Comment by SamuelBrand1** [comment]
I don't have alot of experience with good refactor practise, but this seems a very good idea.

Would it make sense to clear the back-log of two PRs I'm working on at the moment ASAP; then do a refactor today?

**Comment by seabbs** [comment]
yes I think so

**Comment by SamuelBrand1** [comment]
> If we did that then it seems like having things in folders by module might be nice? It seems like its a bit all over the place currently.

By _module_ you mean a sort of work grouping?
