### ISSUE TITLE
Clarity on use of Doc extension tools 

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#126]
I thought we were using the extension tools to manage the construction of the args documentation etc as you had in the original docs PR (and the other similar extension tools). It sounds like this is still in the air though so perhaps we need another discussion issue? What I mean is that yes we have the template but I thought when writing docstrings we would be automating large parts of them using the extension tools to make them less error prone (l;like the arg types).

_Originally posted by @seabbs in https://github.com/CDCgov/Rt-without-renewal/pull/117#discussion_r1516594731_

**Comment by SamuelBrand1** [comment]
My understanding is that we aim for [this](https://docs.sciml.ai/SciMLStyle/stable/#Documentation) for type and function docstrings.

The way we get there is using docstringextensions, but descriptions like `#Arguments` need to go in the DOCSTRING for the template. The types of the arguments are found by TYPEDSIGNATURES.

**Comment by seabbs** [comment]
> The way we get there is using docstringextensions, but descriptions like #Arguments need to go in the DOCSTRING for the template. The types of the arguments are found by TYPEDSIGNATURES.

Yes, issue is about using these which wasn't in the PR that this comment was pulled out of.

**Comment by seabbs** [comment]
Noting that the lack of clarity here is starting to lead to increasing amounts of technical debt as some features are being implemented without any documentation and most have different standards being used. We should aim to resolve this ASAP.

**Comment by SamuelBrand1** [comment]
I think we have clarity now.

`DocStringExtensions.jl` provides annotations in the the template macro but not used elsewhere.
