### ISSUE TITLE
Revisit handling of default priors

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#131]
Default priors are currently handled by small helper functions that have custom names. This seems surprisingly clunky given the rest of the code base. 

Whilst I agree default priors in structs could be dangerous in the hands of some users I also think providing opinionated priors can be very helpful and also guide practice. 

Personally I would vote for default priors in the structs but open to other suggestions?

**Comment by SamuelBrand1** [comment]
My view is that if we can close #133 in such a way that all priors have defaults for their constructor; then this is closed too.

**Comment by seabbs** [comment]
I think this is now resolved? (checked and yes)
