### ISSUE TITLE
Make all constructors have named and not positional arguments.

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#133]
even 

```julia
function AR(;damp_prior::Priors, var_prior::Distribution, init_prior::Priors)
```

here so the constructor is not based on positional args (I realise that this doesn't exist for all structs yet)

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/pull/128#discussion_r1517922322_

**Comment by seabbs** [comment]
Looking through the code there seems to be a lot of variance on this. I think we should agree a clear approach, document it, implement it everywhere, and expect future methods to follow it.

**Comment by SamuelBrand1** [comment]
Breaking this down:

A list of struct types with available constructors with named args:

- [ ] `EpiModel`s and `EpiData`
- [ ] `LatentModel`s
- [ ] `ObservationModel`s
