### ISSUE TITLE
Increase number of `elbo_draws` for pathfinder

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#136]
`manypathfinder` initialisation uses the ELBO estimate of single pathfinder runs to select a good initialisation for NUTS. It maybe that this means that there is utility in increasing the default number of `elbo_draws` used to estimate ELBO.

**Comment by seabbs** [comment]
@SamuelBrand1 is this still in play?

**Comment by SamuelBrand1** [comment]
I think this might be connected to #174 (e.g. does changing this in any sense my default inference more reliable?) but I'm not certain yet. So still in play.

**Comment by seabbs** [comment]
Is this still live?

**Comment by SamuelBrand1** [comment]
Not really.
