### ISSUE TITLE
Documenting pattern for Turing model constructors

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#143]
## Problem

The functions being generated by various `generate_...` functions generated with the `@model` macro return a `DynamicPPL.Model` struct which interfaces with `Turing.jl` sampling methods.

However, simply describing these generated functions as returning a `Model` struct is not very informative to users.

## Proposal

Each function that generates a `Model` struct should also have a docstring section in the pattern of:

---------------------------------------------

### Sampled random variables
...describe the random variables that get sampled....

### Generated quantities
...describe the object that gets generated....

**Comment by seabbs** [comment]
Is this done?
