### ISSUE TITLE
Reorganise the build of documentation

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#144]
As of #132 the code base is split over a number of submodules.

This means that docstrings are not rendered unless we pass a list of submodules to doc to `make.jl`. I would pair this with reorganising the docs so that each submodule gets its own doc page.

**Comment by seabbs** [comment]
Very related (and potentially the new issue is a duplicate) to #275

**Comment by seabbs** [comment]
I think it makes sense to lump this in with #277 as without this the package is going to be very hard to use

**Comment by seabbs** [comment]
Done in #320
