### ISSUE TITLE
Pathfinder with `adtype` kwarg

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#158]
@sethaxen has updated `Pathfinder.jl` to take an `adtype` kwarg to a [`ADTypes.jl`](https://github.com/SciML/ADTypes.jl) struct to choose AD method to use, mentioned [here](https://github.com/mlcolab/Pathfinder.jl/issues/93#issuecomment-2003904032).

Lets try this out.

**Comment by seabbs** [comment]
I think this is now resolved?
