### ISSUE TITLE
General missing data support to all observations models

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#160]
When dealing with #80 I have split delays and the observation model into separate structs. This still leaves a lot of boilerplate in the Negative binomial model that is needed in order to support missing data (even more if wanting to vectorise when we can) and more will be needed to broadcast single cluster factor priors to vectors of the same length as the observation (so that we can naturally support more complex cluster factor models without changing the observation model. 

I think it makes sense to construct an internal struct and then dispatch on this to methods that are either vectorised or use a for loop and then call a supplied function.

I have done a bit of scaffold work on that here but paused to finish up #80. 

```julia

struct ObswithMissing{F <: Function, I <: AbstractVector{<:Union{Real, Missing}}, L <: AbstractVector{<:Real}} <: AbstractObservationModel
    model::F
    o_t::I
    O_t:L
    params::NamedTuple

    function ObswithMissing(model::Function, o_t::AbstractVector{<:Union{Real, Missing}}, params::AbstractVector)
        new_params = NamedTuple{(:params,), Tuple{AbstractVector}}((params,))
        for i in eachindex(params)
            if length(params[i]) == 1
                new_params[i] = fill(params[i], length(obs))
            end
        end
        return new{typeof(model), typeof(obs), typeof(new_params)}(model, obs, new_params)
    end

    # Custom constructor for entirely missing obs
    function ObswithMissing(model::Function, obs::AbstractVector, params::AbstractVector)
        obs = Vector{eltype(Y_t)}(undef, length(Y_t))
        return ObswithMissing(model, obs, params)
    end
end

@model function EpiAwareBase.generate_observations(obs_model::NegativeBinomialError,
    y_t,
    Y_t)
cluster_factor ~ obs_model.cluster_factor_prior

if ismissing(y_t)
y_t = Vector{Int}(undef, length(Y_t))
end

return generate_observations(obs_model, y_t, Y_t, cluster_factor)
end

# Vectorized implementation for when there are no missing values
@model function generate_observations(,
y_t::Vector{<:Integer},
Y_t::Vector{<:Real},
cluster_factor)
y_t .~ NegativeBinomialMeanClust.(Y_t .+ obs_model.pos_shift, cluster_factor^2)
return y_t, (; cluster_factor,)
end

# Loop-based implementation for when there are missing values
@model function generate_observations(obs_model::NegativeBinomialError,
y_t::Vector{Union{Missing, Integer}},
Y_t::Vector{<:Real},
cluster_factor)
for i in eachindex(y_t, Y_t)
y_t[i] ~ NegativeBinomialMeanClust(Y_t[i] + obs_model.pos_shift, cluster_factor^2)
end
return y_t, (; cluster_factor,)
end
```

**Comment by SamuelBrand1** [comment]
> I think it makes sense to construct an internal struct and then dispatch on this to methods that are either vectorised or use a for loop and then call a supplied function.

I think this makes the most sense here.

**Comment by seabbs** [comment]
Now that we have #182 in place we have more than one observation model and so this now makes sense to implement before we think about adding any more obs models. That being said I think its still fairly low priority vs other functionality.
