### ISSUE TITLE
Appropriate getting started tutorial and defaults

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#174]
I was just trying out a lower variance neg bin sampling... I think deciding the appropriate defaults is an issue.

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/pull/173#discussion_r1540834169_

I think we need to reconsider the getting started example. The default model to demonstrate should be a renewal model, in my opinion.

Also, the direct infections model probably shouldn't have negative binomial sampling? It rather obviously difficult to identify compared to latent process variation in a way that (say) a renewal model wouldn't find problematic.

**Comment by seabbs** [comment]
Agree

**Comment by seabbs** [comment]
#169 Introduced quite a few changes in how we handle model objects so we now need to also reflect these a bit better in a the getting started tutorial.
