### ISSUE TITLE
Standard approach to multiple group/ multi-signal modelling

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#176]
## Multi-group modelling

At the moment all our methodology is predicated on one dimensional time series, either infections, cases or driving latent processes. In general, we'll want all of the above to be potentially higher dimensional.

This brings up some issues:
- How to design intuitive API for linking methods for connecting processes of different dimension/size.
- What kind of Julia object are the multi-dimensional objects?

My view on the second issue here is that we should have each process sample paths as something like `Vector{Union{Array{T},T}} where T <: Number` parametric types. The reason is that time index is trivially associated with the index of the vector, but each time point can be an arbitrary Array. I think that this finds a sweet point between generality and convenience and also opens up using utilities like [RecursiveArrayTools.jl](https://github.com/SciML/RecursiveArrayTools.jl).

**Comment by seabbs** [comment]
Note that some of this is linked to #161 as we may not always be able to depend on broadcasting rules based on the structure supplied to `EpiProblem`

**Comment by SamuelBrand1** [comment]
Yes, this is a good point.
