### ISSUE TITLE
Add Poisson Error observation model

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#181]
We currently have a Negative Binomial error model which we can stack with other observation models, but no Poisson error model.

I think this is a lapse for two reasons:

- Poisson is an important baseline.
- Neg Bin can be understood as a Poisson with a latent Gamma multiplicative factor on mean observations which is iid across observation events. However, we now are considering other latent factors on mean observations (e.g. periodic effects). I realise its fairly standard in the literature to have both of these, but I would like to be able to try this without Neg bin errors.

_NB:_ I realise that mathematically we can effectively recover Poisson sampling by setting the overdispersion of the Neg bin towards a limit but I don't think this is always a clean code style or numerically stable approach.

**Comment by seabbs** [comment]
I don't think this is a priority unless it is in the analysis plan but agree it should be easy to add.
