### ISSUE TITLE
Past sequence of latent infections for initial case representation

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#183]
At the moment, we use an initialisation procedure inside `Renewal` model:

https://github.com/CDCgov/Rt-without-renewal/blob/9a3a519548a9741988d859ab86f81cf26425ef91/EpiAware/src/EpiInfModels/Renewal.jl#L164-L166

This creates (temporarily) a vector of past latent infections based on the sampled initial value of the reproductive number (which is converted into an exponential growth rate $r$).

It might be a good idea to extend this concept to a modular plug-in; in particular this would allow generation of sensible cases early in a time series.

**Comment by seabbs** [comment]
I think we might want to think about the renewal initialisation seperately from the problem of observations depending on past latent infections?

I was assuming here that we would automatically buffer the input time index with some index index in the latent proceess? If we were to do this though we would need to think about how to pass in metadata for the Rt etc of these days. One option could be to make two ways to do this. One where we increase the time index backwards for the latent process (which is the easiest solution) and one where we restrict which time indexes are included in the obs model (the easiest when there is time indexed latent information forr the latent process).
