### ISSUE TITLE
Improve combination tests

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#186]
We are still adding unit tests (see #179 and #180) but are lacking tests that cover combinations of model components (e.g. combinations of latent models and observations models) _and_ we are lacking tests that cover multiple AD paradigms (e.g. ForwardDiff, tape-based reverse AD, source-based reverse AD etc).

**Comment by seabbs** [comment]
I think you have some work on this @SamuelBrand1 is it in a WIP branch?

**Comment by SamuelBrand1** [comment]
We've resolved:

- AD tests (covered by TuringBenchmarks).
- We now test a combination set of IGPs and latent models whilst fixing a delay observation model.

Q: Does #371 close this and we have new issues for the newer models going forwards?

**Comment by seabbs** [comment]
yes I tihnk so
