### ISSUE TITLE
simulate_or_infer or simulate and infer

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#208]
In #204 a new function `simulate_or_infer` was introduced that dispatches to simulation or inference code depending on the type of struct passed (in the latter case it will once this is implemented in a future PR). Its currently unclear if this abstraction is helpful or just provides another layer of complexity. 

Once the `simulate_or_infer` inference method is implemented we should circle back to this issue and discuss the relative merits of both approaches in order to reduce our technical debt going forward. It is hard to have this conversation first as for me at least its hard to picture the relative merits in abstract.

**Comment by SamuelBrand1** [comment]
In light of #217 is this still an issue? Genuine question... I think we still want to split this because we're not really using dispatch in a particularly useful way?

**Comment by seabbs** [comment]
Yes exactly
