### ISSUE TITLE
Stochastic failure is negative binomial which is an epiaware issue. Aside from updating the name this is good to go.

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#242]
Stochastic failure is negative binomial which is an epiaware issue. Aside from updating the name this is good to go.

_Originally posted by @seabbs in https://github.com/CDCgov/Rt-without-renewal/issues/236#issuecomment-2137166004_

**Comment by seabbs** [comment]
@SamuelBrand1 can you refine this issue a bit so someone else (i.e. not me or you) could target it?

**Comment by SamuelBrand1** [comment]
Yeah, the stochastic failure was [here](https://github.com/CDCgov/Rt-without-renewal/blob/9bd704393c336c0fec57809e3beca4b6b1c55cef/EpiAware/test/EpiObsModels/ObservationErrorModels/NegativeBinomialError.jl#L42-L43). 

In the other similar tests we use something with a p value that means that conditional on the test being correct stochastic failure is very rare; this unit test probably want to go that way (unless there is an argument that we will get too many false passes).

**Comment by seabbs** [comment]
I'm going to close as this has resolved but we still need better integration testing (but I think that should be its own issue)
