### ISSUE TITLE
Bounded population size as default

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#244]
Another more radical possibility is that we accept that having models that _can_ sample > `1e17` infections (which is easier to do in unbounded pops than one might expect due to RW $\log R_t$ and the magic of exponential growth) are bad and enforce a max population size. Then these warm up phase problems should disappear in a more principled way.

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/issues/237#issuecomment-2139307623_
           
We haven't done this because we are much more focused on other factors in the analysis, but it would help the sampling during edge cases in warm up.

**Comment by seabbs** [comment]
I don't think we should have this as a default but I do think we should have a clear path to making this a composable feature and other similar ideas like feedbacking Rt based on incidence etc that proxy this.

**Comment by SamuelBrand1** [comment]
> I don't think we should have this as a default but I do think we should have a clear path to making this a composable feature and other similar ideas like feedbacking Rt based on incidence etc that proxy this.
> 
> In my head this would either be a generalisation of the current `Renewal` infection model to multiple more complex types or it would be making this somehow specifiable in the way we are handling latent models and observation models. The tricky bit here is that you need to loop over infections to do this in most (nearly all?) cases and so nesting models based on vector passing is tricky

My vote is for generalisation of the infection generating process (igp) model. I think we set the behaviour of the igp by the type, then it has its own callable for generating the infections. The trick here is to create an abstract `Renewal` type for `generate_latent_infs` to dispatch on with the specific renewal models (e.g. no population, infection reduced by fraction of remaining pop, recent feedback) behaviour in the callable.

**Comment by seabbs** [comment]
After this PR my concerns remain about stacking multiple processes
