### ISSUE TITLE
Include day of week effect in pipeline analysis

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#257]
This looks great!

Wrt using `softmax`, I think that would be cool after we clear #251 e.g. we might model a weekly process but then broadcast out the weekly observations to a day of the week in a way that respects the weekly average obs. 

This implementation hit a different form of modelling and looks nice! 

Note: this was part of analysis plan and should now be added to pipeline.

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/pull/253#pullrequestreview-2096131916_
            
As per title in light of this PR

**Comment by seabbs** [comment]
Linked to #258

**Comment by SamuelBrand1** [comment]
This is moving forward now #258 is closed.
