### ISSUE TITLE
Add softmax to broadcast_dayofweek

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#258]
#253 added a new helper to construct day of the week ascertainment models. 

In the review of that PR (and elsewhere) it was noted that it might make sense to constrain the within week model to sum to 7 using a `LogExpFunctions.softmax`. This makes sense to provide as the default I think. 

To do this we would need to add a `TransformLatentModel` wrapper to the `latent_model` passed to `broadcast_dayofweek`.

**Comment by SamuelBrand1** [comment]
This is a nice functionality, but should it be default? As mentioned in #253 the current implementation (some daily scale application) is probably the most common form of weekly periodic effect in observations used in modelling.

**Comment by seabbs** [comment]
I think it is effectively the same but constrained (at least how I am thinking about it) so it seems reasonable to make it a default in this kind of helper (in the world of implementing helpers for good ideas).
