### ISSUE TITLE
Continuously benchmark performance

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#274]
`epinowcast` uses `{touchstone}` for continuous benchmarking of PRs (see https://github.com/epinowcast/epinowcast/pull/464#issuecomment-2115829621). This is very useful when making proposed model "improvements" as it gives a very clear sanity check of if it is an improvement.

This would have been very useful to us for catching #269 faster and automating the identification of the cause. This suggests to me it is only going to be more useful going forward. 

In the Julia world we have `BenchmarksTools.jl` which is nice and it seems like there is an integration with this https://github.com/benchmark-action/github-action-benchmark action which seems like it would do nearly everything we might want apart from giving a clear indicator in PR (like `touchstone` does). 

Another option we could take would be to commit some output from `BenchmarkTools.jl` (which is what @kaitejohnson did in their wastewater work for scores) for runtimes this might not be ideal as you need to have timings from the server where CI is running. 

A final option would be to replicate `touchstone` in julia. i.e running both the target and proposed code on the same CI machine and comparing run times and then reporting.

**Comment by SamuelBrand1** [comment]
The benchmark-action does look really good... I like the charting:

https://github.com/benchmark-action/github-action-benchmark?tab=readme-ov-file#charts-on-github-pages

**Comment by seabbs** [comment]
The only thing I am unclear about is what happens with PRs vs already merged code. Ideally we would catch performance regressions before they were merged. 

One option I see is to use the continuous benchmarks on `main` and then reuse the benchmarks and write small CI wrapper that checks out the two branches and compares the results (this seems like it would be quite easy to do?
