### ISSUE TITLE
"Hints and tips" documentation

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#276]
As Julia is so modular we have no need to reimplement some of our helper functionality as it can be used from other packages. However, this attitude across the Julia ecosystem makes packages very hard to use for everyone but experts. 

I think a way to mitigate this might be to have a hints and tips section (or something like useful functionality from other packages) where we collect some of these ideas.

Things that come to mind are: 

- Remaking objects using `Accessors.jl` (#90)
- Conditioning on Turing models using `|` and `condition`
- Tools to access parts `MCMCChain` objects and to visualise them for diagnostics etc.

_Are there any examples of good practice at this in the ecosystem we can be inspired by?_

**Comment by SamuelBrand1** [comment]
Also, we have cover _some_ of this in the `EpiAware` `README` but opinions on nice Julia set ups e.g. having `Revise.jl` `TestEnv.jl` etc in the basic environment of your local Julia installation.

**Comment by SamuelBrand1** [comment]
Opinions on setting up VS-Code to run nicely, setting up REPL to be a quick interface to running example Julia code. For example, hardly anyone seems to know about `(@v1.10) pkg> activate --temp` to make a quick fire-and-forget environment to try out (say) the Turing examples in.

**Comment by SamuelBrand1** [comment]
Quick thoughts:

- Using `Arviz.jl` examples
- Some examples based on using `RCall` or conversely `JuliaCall` from R e.g. running `EpiAware` from R (RStudio editor) and then getting the chain info back to do your favourite `tidybayes` based workflow?

**Comment by seabbs** [comment]
It sounds like we agree this is a good idea. I think step 1 is making the skeleton and step 2 (likely a new issue or series of issues is content). That should help manage PRs

**Comment by seabbs** [comment]
Assuming we lumping the skeleton in with the getting started assigning @SamuelBrand1

**Comment by seabbs** [comment]
The new getting started with julia (i.e #301) resolved a lot of the Julia level questions here. Now I think wee need a doc which

**Comment by seabbs** [comment]
The skeleton for this is in place and now just needs some content
