### ISSUE TITLE
Better getting started with Julia documentation

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#277]
Also, we have cover _some_ of this in the `EpiAware` `README` but opinions on nice Julia set ups e.g. having `Revise.jl` `TestEnv.jl` etc in the basic environment of your local Julia installation.

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/issues/276#issuecomment-2162640798_
            
Splitting this out because its separate to opinions of `EpiAware` workflow using other packages.

**Comment by seabbs** [comment]
@SamuelBrand1 do you think you have some capacity to work on this in the near term? I think it might be best coming from you in the first instance.

**Comment by SamuelBrand1** [comment]
Yes, but it'll be fourth on priority list. It shouldn't take long though. When I get brain fog on a dev problem I'll go on this.
