### ISSUE TITLE
Specific inference targets decision

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#281]
At the moment our analysis plan for posterior posterior prediction evaluation is:

> - We fit each model to each day for each time-series being evaluated
> - We visualise posterior predictions of all measures.
> - We assess coverage, the CRPS, and CRPS of log-transformed data for all observables.
> - We scale all metrics where possible by the performance of the renewal process infection-generating model and stratify by the target measure.
> - As well as reporting overall metrics we also report performance by horizon aggregated by week for the following horizons (-4, -2, -1, 0, 1, 2) and over time.
> - We report performance both overall and by scenario and case study

We should be more specific about "all measures". 

My vote is to target:

1. Case forecast.
2. Latent $R_t$ over all time points.
3. Recovering day of week effect.
4. _Maybe_ cluster factor of observation process.

**Comment by seabbs** [comment]
Are we decided on this or more to discuss?

**Comment by SamuelBrand1** [comment]
I think this is decided.
