### ISSUE TITLE
Preliminary results from pipeline

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#284]
Since issue #195 is nearly completed pending decision on #282 I think we can go with this, _albeit_ with consideration that plenty of refinement is coming e.g. #243 , #225, #24.

### Tasks

- [x] #288
- [x] #287
- [x] #292
- [x] Run locally.

**Comment by seabbs** [comment]
This is done right? We just need issues for post processing the output (i.e scoring and visualisation) which is the current focus + issues for fine tuning the input to take it from an example output to something we have some faith in
