### ISSUE TITLE
Sampling noise prior

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/Rt-without-renewal#29]
https://github.com/CDCgov/Rt-without-renewal/blob/f7bf1c6f34ae9f40e76b53ff17ad865f98b2ca78/EpiAware/src/models.jl#L10

Let's think about this prior a bit in a new issue. It's a reasonable prior, but I think the PC prior using the inverse square root is usually recommended? This is on 1/k so it's close but not exactly the same. But sampling from that prior has also behaved pretty poorly for me.....

@seabbs -- I know you have thoughts here.

_Originally posted by @zsusswein in https://github.com/CDCgov/Rt-without-renewal/pull/28#discussion_r1486369014_

**Comment by seabbs** [comment]
So I don't really have thoughts and more just use the recommended parameterization in the stan community. 

https://github.com/stan-dev/rstanarm/issues/275

I would usually do `1/sqrt(aux); aux ~ Halfnormal(0,1)` and tune the standard deviation until I thought my overdispersion was reasonable.

**Comment by SamuelBrand1** [comment]
Yeah I can see why they do that from the link.

**Comment by zsusswein** [comment]
Yeah it makes good sense and the PC prior math is super cool. My concern is that (at least in these settings) it doesn't seem to be working that well empirically. It seems like the prior is generally much stronger than the information in the data and the parameter is generally poorly sampled.

Now that I'm thinking it through, perhaps it does makes sense to go with the recommended Stan default and see if any of the latent processes makes a difference in sampling. Perhaps worth revisiting this issue after all the latent processes are set up and we can look at prior predictive distributions?

**Comment by seabbs** [comment]
>  It seems like the prior is generally much stronger than the information in the data and the parameter is generally poorly sampled.

I think this is more a general case of trying to estimate overdispersion in these models vs the specific transform. I more think the conclusion is that a tighter prior on `aux` is often needed vs that is given. 

I am happy to stick with what we have here or to revisit. 

What is the current setting in the ww work? Perhaps we can agree to use that for now and revisit in 1.5?

**Comment by seabbs** [comment]
Where are we on this? Is it backlog for a future milestone vs `0.1.0`?
