### ISSUE TITLE
Add population constraints to pipeline

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#291]
During testing for #290 I noted that forecasts that were reasonable for underlying latent process, the forecasts could be unreasonable for cases (e.g. explosive growth). A simple fix would be including the population constraints into the modelling as per new `EpiAware` functionality.

**Comment by seabbs** [comment]
This isn't in the analysis plan and also doesn't really represent a "standard" so I would vote to hold on this for now. Potentially a prior tweak would help in the first case.

**Comment by seabbs** [comment]
Status?

**Comment by SamuelBrand1** [comment]
I've dropped this as per not in the analysis plan.
