### ISSUE TITLE
Abstract type for simulating cases

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#294]
Currently generating data, e.g. using `data = missing` patterns returns a `Vector{Union{Missing, Real}}` type object. This is known to be poorly performant because `Real` is an abstract type ( https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-abstract-container ).

This is not a priority issue, but worth flagging. A potential fix would probably involve the model looking at its error model, and making type specification e.g. `PoissonError` would specify a concrete integer type. That would be slightly awkward at the moment.

**Comment by seabbs** [comment]
Could you flesh this out a bit please sam?

**Comment by SamuelBrand1** [comment]
We no longer do this so closing
