### ISSUE TITLE
Visualisations to be done with `Arviz.jl`?

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#305]
We had a soft focus on producing model analysis output in a `tidybayes` compliant format (hence the existence of the `spread_draws` function in `EpiAware`.

However, I think [`Arviz.jl`](https://julia.arviz.org/ArviZ/stable/) looks potentially more promising, without necessarily cutting off `tidybayes` approach.

My reasons:

- Can be incorporated natively in a Julia workflow.
- Seems very nicely featured.
- Can save to data which `arviz` users in other langs (e.g. python) can access to check out the analysis.
- Specific to above, makes its easier to cross compare to where the MSR project is going (https://github.com/CDCgov/multisignal-epi-inference/issues/200).

**Comment by seabbs** [comment]
Agree

**Comment by SamuelBrand1** [comment]
This is a blocked for our naming scheme by https://github.com/arviz-devs/ArviZ.jl/issues/211.

But could be resolved by https://github.com/arviz-devs/ArviZ.jl/pull/347 (looks like compat issues need resolved with `ArvizPythonPlots`)

**Comment by seabbs** [comment]
I think we can close this? We have it the FAQ as something to use and will use it when we write more docs. I don't think we expect to write custom functionality using it at this time?
