### ISSUE TITLE
AlgebraOfGraphics plotting for pipeline

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#311]
Given the plotting block for `Arviz` (see issue #305 )... from alternate discussion with @seabbs I've checked out `AlgebraOfGraphics.jl` https://aog.makie.org/stable/generated/penguins/ Which looks very nice. 

The objective here is experimentation with clean plotting interfaces for pipeline results.

**Comment by seabbs** [comment]
I think this is done for now?
