### ISSUE TITLE
Robustness against stochastic failure in test CI

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#318]
I note that #314 got bumped from the merge queue due to an occasional stochastic failure... despite this PR not being concerned with `EpiAware`.

what is the best way to build resilience here without causing false pass checks? Maybe fixing the rand seed?

**Comment by seabbs** [comment]
Yes I think fixing the seed here and generally makes a lot of sense

**Comment by seabbs** [comment]
Good point. Is there really no ability to run across test setup code?

**Comment by SamuelBrand1** [comment]
Looks like this is coming https://github.com/julia-vscode/TestItemRunner.jl/pull/57

AFAIK its blocked by integration into VS-code test suite.

**Comment by SamuelBrand1** [comment]
Things moving here

https://github.com/julia-vscode/TestItemRunner.jl/pull/57#issuecomment-2212396718

**Comment by SamuelBrand1** [comment]
Alternate suggestion from f2f discussion is an `EpiAware` submodule with test utility functions.

**Comment by SamuelBrand1** [comment]
This is covered by #419 .
