### ISSUE TITLE
Include all code blocks in `replication` example

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#319]
From f2f conversation, some people find the hidden code blocks generating the plots in the "getting started" example confusing and would prefer if these were visible.

**Comment by seabbs** [comment]
@kaitejohnson reports that the current pluto based website tutorials are not runnable for users who try and copy and paste the code blocks into the REPL (which is a natural thing to do). Aside from not showing the plotting code we are also not surfacing the dependencies that are being used. 

I looked at pluto side solutions to using and it would be very clunky to break everything up into individual level blocks (which is what it seems like it would need). 

Can the conversion to the Documenter docs be changed so this code is shown? 

I think this issue means our docs are largely unusable for new users and calls into question the pluto based approach if we can't fix asap.

**Comment by SamuelBrand1** [comment]
> I looked at pluto side solutions to using and it would be very clunky to break everything up into individual level blocks (which is what it seems like it would need).

Is the clunkiness here `begin ... end` blocks?

**Comment by SamuelBrand1** [comment]
As in is rerunning with all the code blocks set to visible a reasonable solution?

**Comment by SamuelBrand1** [comment]
Its a pretty easy fix to make all code blocks visible and add some extra description. I'm going to drop a quick PR on this.
