### ISSUE TITLE
git ignore manifest.toml

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#32]
When EpiAware is stable community posts suggest that good practice is to depend on the `Package.toml` and to therefore `.gitignore` the manifest. This is also helpful as it avoids frequent merge issues during development due to differing package versions etc.

**Comment by SamuelBrand1** [comment]
Agreed.

**Comment by seabbs** [comment]
Due you have a read on when we should do this? I almost think it should be sooner rather than later?
