### ISSUE TITLE
Use regex to enable doctests for random output

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#333]
Ideally we would be able to show output from random processes in our documentation. To do this we need it to be a doctest. unfortunately attempts to set the seed across OSs don't seem to be stable so this obvious approach is a no go. 

Instead we can use Documenter functionality to regex out all numbers from the output so that only the structure is compared. For single values this appears to work. Sadly for more complex objects like below we see it doesn't work. Making this work would unlock better examples and easier doc tests 

```julia
@doc raw"
Extract a parameter array from a `Chains` object `chn` that matches the shape of number of sample
and chain pairs in `chn`.

# Arguments
- `chn::Chains`: The `Chains` object containing the MCMC samples.

# Returns
- `param_array`: An array of parameter samples, where each element corresponds to a single
MCMC sample as a `NamedTuple`.

# Example

Sampling from a simple model which has both scalar and vector quantity random variables across
4 chains.

```jldoctest; filter = r\"\b\d+(\.\d+)?\b\" => \"*\"
using Turing, MCMCChains, EpiAware

@model function testmodel()
    y ~ Normal()
end
mdl = testmodel()
chn = sample(mdl, Prior(), MCMCSerial(), 2, 1, progress=false)

A = get_param_array(chn)
# output
2×1 Matrix{@NamedTuple{iteration::Int64, chain::Int64, y::Float64, lp::Float64}}:
 (iteration = 1, chain = 1, y = 1.2817564703577078, lp = -1.7403883578565975)
 (iteration = 2, chain = 1, y = 0.7259423762267098, lp = -1.1824347000055138)
```
"
function get_param_array(chn::Chains)
    rowtable(chn) |> x -> reshape(x, size(chn, 1), size(chn, 3))
end
```

**Comment by SamuelBrand1** [comment]
Added context: This is the recommended way of dealing with non-deterministic output of the docstring https://documenter.juliadocs.org/stable/man/doctests/#Filtering-Doctests

**Comment by seabbs** [comment]
I'm not clear how to take this forward. Is this worth opening a issue with `Documenter.jl` or is it just the case of finding the right regex?

**Comment by SamuelBrand1** [comment]
In #510 we've gone with using doctests as "run" tests, with a lean towards to augmenting the main docs. Testing of random processes has ended up being based on statistical tests.

Maybe time to close this as unplanned?

**Comment by seabbs** [comment]
I still think this cold be nice as a way of testing something is correct in the docstrings but I don't feel that strongly

**Comment by seabbs** [comment]
i.e its better than the nothing pattern but perhaps is still too brittle

**Comment by SamuelBrand1** [comment]
Yeah, to be used carefully.
