### ISSUE TITLE
Fix scan reversediff issue

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#338]
This currently prevents benchmarks being run on `Renewal`. Any fix should check these and integrate them into the wider benchmarking backend.

https://github.com/CDCgov/Rt-without-renewal/blob/eacfd5798de1403f0885576c8209f64969dce5dc/benchmark/bench/EpiInfModels/Renewal.jl#L1

**Comment by SamuelBrand1** [comment]
I'm a bit confused by this one, because if we have hard-typed a variable somewhere as `Float64` when `ReverseDiff` needed to overload as `TrackedReal` we should have code failure in other areas (e.g. the getting started example(s))

**Comment by seabbs** [comment]
Yes its a poser. I haven't inspected the guts of what `TuringBenchmarks` is doing so perhaps there is some difference vs what we are doing elsewhere.

**Comment by seabbs** [comment]
Closing as not doing due to #384
