### ISSUE TITLE
Improve docstrings

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#35]
Can we improve our docstring practice to reduce duplication, improve clarity and generally set a standard?

I see this suggestion for python which seems to make sense to me: https://numpydoc.readthedocs.io/en/latest/example.html#example

In particular I like the lack of repetition of the function arguments, the use of doctests, and the use of a clear summary section and notes section for further details

Are there resources from the Julia community we could point at to justify/improve our practice?

**Comment by SamuelBrand1** [comment]
https://github.com/JuliaDocs/DocStringExtensions.jl

**Comment by SamuelBrand1** [comment]
Since we are using the SciML style for formatting; I assume we are going to use the SciML preferred documentation [conventions](https://github.com/SciML/SciMLStyle?tab=readme-ov-file#documentation)?

**Comment by seabbs** [comment]
what do you think? I think yes and its good to follow established standards and it seems like a high quality ecosystem

**Comment by SamuelBrand1** [comment]
> This makes me wonder if we do need this template builder for the doc strings or not?

Which template builder? `DocStringExtensions`? 

I think its handy.

**Comment by SamuelBrand1** [comment]
@seabbs @zsusswein 
I've started putting this in on this [branch](https://github.com/CDCgov/Rt-without-renewal/tree/81-document); although far from finished version.

But have a look to see if that the level of doc you want.

**Comment by seabbs** [comment]
> Which template builder? DocStringExtensions?

Yes and to be clear i would like to  use it but not going to force the it on anyone

**Comment by seabbs** [comment]
@SamuelBrand1 could you make make some sub issues for parts that still need docs so someone else can pick this up?

**Comment by SamuelBrand1** [comment]
> @SamuelBrand1 could you make make some sub issues for parts that still need docs so someone else can pick this up?

Yes, and not sure why I didn't just do that!

**Comment by SamuelBrand1** [comment]
Basically, I'm happy on that branch _until_ the bit documenting the callable of `Renewal`... thats clunky due to LaTeX strings (sure there is a better way).

Fairly random thoughts:
1. `DocStringExtensions` is probably most useful deployed asap, because it reduces the work load of redocumenting breaking changes.
2. I haven't used [`DocStringExtensions.@template`](https://docstringextensions.juliadocs.org/stable/#DocStringExtensions.@template) but it looks handy? Again the kind of thing to set up before extensive documentation to save time.

**Comment by seabbs** [comment]
> I haven't used [DocStringExtensions.@template](https://docstringextensions.juliadocs.org/stable/#DocStringExtensions.@template) but it looks handy? Again the kind of thing to set up before extensive documentation to save time.

Yes I think this is a good idea.

**Comment by SamuelBrand1** [comment]
Lets break this down:

- [ ] Finalize template, doc the `EpiAware` module and the abstract types and fall-back methods that dispatch on them as the most general case.
- [ ] doc the `utils`
- [ ] doc the `epimodels`
- [ ] doc the `latentmodels`
- [ ] doc the `observationmodels`
- [ ] doc the `inferencemethods`

**Comment by SamuelBrand1** [comment]
Something to [note](https://docs.sciml.ai/SciMLStyle/stable/#documentation): 

> The @doc doc""" """ formulation from the Markdown standard library should be used whenever there is LaTeX.

**Comment by seabbs** [comment]
This has been incrementally resolved by multiple PRs
