### ISSUE TITLE
Expand unit testing to include more NUTs based parameter recovery

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#368]
Our unit testing currently covers sampling properties of all functions and our benchmarks cover the ability to calculate gradients. Potentially we might want to expand testing to see if key parameters can be recovered by NUTs (i.e simulate from the prior model and fit w/ high tolerances)? 

Potentially this would give us warnings of issues but it would increase the length of our testing and could easily not add that much value (especially given the existence of gradient checks in the benchmarks).

This came up in #358

**Comment by SamuelBrand1** [comment]
If it is merged does #371 close this?
