### ISSUE TITLE
Work out how to vary the ylims subplot by subplot in AOG

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#376]
> Nice looks good. I am a bit surprised you've needed to make subplots and compose vs using `AlgebraofGraphics` facet mechanics (which is what I would do if making this in `ggplot2` for example.

My problem here was that I/search engines couldn't work out how to vary the ylims figure by figure... I'm being a bit basic here I think. I agree because unlike the first pass fig 1 now the subplots are slightly different sized.

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/issues/375#issuecomment-2233452358_

**Comment by SamuelBrand1** [comment]
Noting @seabbs suggestion to add `ylims` the dataframe (apparently this is `ggplot` style)

**Comment by SamuelBrand1** [comment]
Update... using `draw` to create a figure grid and its easy to interact with the `limits` of each grid directly. Using `draw!` onto a mixed figure (which makes it easier to do other things like adding text areas) and its not so easy.

**Comment by seabbs** [comment]
Got you makes sense

**Comment by SamuelBrand1** [comment]
Resolved by moving to using `Makie` imperatively.
