### ISSUE TITLE
Modular interface between fixed data of inference problem and the `Turing` model implementing the inference problem

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#38]
## Interface

Atm, the toy model merged in #33 ingests an `EpiModel` struct which contains data that we are treating as fixed for the purposes of this project into a `Turing` model called `log_infections`.

This fixes how any latent process generates underlying infections at the level of separate `Turing models` and therefore implies a substantial amount of repeated code.

## Change to interface

The proposal is for the generative process to dispatch on _either_ the type of the fixed data struct _or_ from a function which is a field of the fixed data struct.

### Options

1. Define concrete subtypes, e.g. `DirectInfections <: AbstractEpiModel` which dispatch a particular method for latent process -> infections.
2. Add another field to `EpiModel` which is the function that does latent process -> infections.

Personal preference is 1. because I think that the pattern

```julia
... data wrangling...

epimdl = DirectInfections(my_distributions...)
my_inference_results = do_inference(data, epimdl...)
```
where `do_inference` is an abstraction on top of `Turing` sampling from the model is easier to understand than

```julia
... data wrangling...

epimdl = EpiModel(my_distributions..., direct_infections_func)
my_inference_results = do_inference(data, epimdl...)
```

But I don't have a very strong preference here.

**Comment by seabbs** [comment]
Yes I much prefer option 1 I think. @zsusswein what do you think?

**Comment by seabbs** [comment]
For others this is the  branch where option 1 has been implemented: https://github.com/CDCgov/Rt-without-renewal/tree/38-modular-inference

A note that `epi_inference` or `do_inference` seem like somewhat odd names for what is still a model constructor if I am not mistaken (i.e the inference model has been constructed but no inference has happened). 

If we were going to generalise this to other parts of the code base (namely going from infections to some likelihood) this pattern would all stick work well? It might be nice to have that as part of this feature PR as well imo so we can be sure its extensible (I see no reason why it wouldn't be).

**Comment by seabbs** [comment]
Two additional notes - should we be handling latent_process differently given this and should we be trying to think of all of these steps as submodels from the get go? Everything else apart from the renewal seems like it is on the face of it but there is a world where you might like a generation time that is based on a prior (or jointly estimated). We could also consider these things out of scope for this project.

**Comment by SamuelBrand1** [comment]
> A note that `epi_inference` or `do_inference` seem like somewhat odd names for what is still a model constructor if I am not mistaken (i.e the inference model has been constructed but no inference has happened).

I'm not particularly connected to a name and open to changing it for reason you give.

#### Background

I think there is a problem with overloading the word "model" here.

What [`@model`](https://turinglang.org/DynamicPPL.jl/stable/api/#DynamicPPL.@model) macro is doing is specifying a set of methods which you can use to generate a instance of a [`Model`](https://turinglang.org/DynamicPPL.jl/stable/api/#DynamicPPL.Model) struct; rather than using the direct `Model` constructor.

Maybe `make_epi_inference_model`? Too verbose?

**Comment by SamuelBrand1** [comment]
So here is a diagram of the basic idea.


```mermaid
flowchart TD

    A["Underlying dists.
---------------------
EpiData"]

    B["Choice of target 
for latent process
---------------------
DirectInfections
    ExpGrowthRate
    Renewal"]

C["Observational Data
---------------------
Obs. cases y_t"]
D["Latent processes
---------------------
Random Walk"] 
E[Turing model constructor]
F["Latent Process priors"]
G[Posterior draws]
H[Posterior checking]
I[Post-processing]
DataW[Data wrangling and QC]

    A --> EpiModel
    B --> EpiModel
    EpiModel -->E
    C-->E
    D-->|random_walk| E
F-->|default_rw_priors|E
E-.->|sample...NUTS...| G
G-.->H
H-.->I
DataW-.->C
```

**Comment by SamuelBrand1** [comment]
> Or just make_inference_model maybe as its already in an epi package (or do we need to aim for ecosystem unique names?)

I don't have strong opinions on naming convention, but happy to go with a suggestion here.

**Comment by seabbs** [comment]
> do we need to aim for ecosystem unique names?)

?
