### ISSUE TITLE
Edit source on website link broken

### ISSUE THREAD

**Issue by athowes** [CDCgov/Rt-without-renewal#410]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/e6a47f7a-f41c-4844-a97b-74fac66b4495">

When I click on the "edit source on website" it takes me to 404:

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/2b89a0f4-4f0a-46c9-b21a-d1c81f25260a">

**Comment by seabbs** [comment]
This is related to #114 and requires us to not have the package as a subdirectory in order to fix. This will happen once we have spun out the package from this analysis so I think this is a not fix as it should resolve itself.
