### ISSUE TITLE
Make Mishra et al replication a full replication

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#420]
At the moment the latent AR process for $\log R_t$ showcase of _Mishra et al_ is still really showcase of the broadcasting of `EpiAware`. Demoing that should be a different part of the docs. I propose actually showcasing the replication by moving the _getting started with epiaware_ stuff away and replicating the daily increments in the AR process.

**Comment by seabbs** [comment]
Yes, strongly agree

**Comment by SamuelBrand1** [comment]
Closed by #442
