### ISSUE TITLE
Bump `Turing` version

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#423]
At the moment, the versions we use of deps in `EpiAware` are:

>   [47edcb42] ADTypes v1.7.1
  [80f14c24] AbstractMCMC v5.2.0
  [0bf59076] AdvancedHMC v0.6.1
  [1313f7d8] DataFramesMeta v0.15.3
  [31c24e10] Distributions v0.25.110
  [ffbed154] DocStringExtensions v0.9.3
⌅ [366bfd00] DynamicPPL v0.27.2
  [1a297f60] FillArrays v1.11.0
  [2ab3a3ac] LogExpFunctions v0.3.28
  [c7f686f2] MCMCChains v6.0.6
  [b1d3bc72] Pathfinder v0.8.8
  [1fd47b50] QuadGK v2.10.1
  [189a3867] Reexport v1.2.2
  [bd369af6] Tables v1.12.0
⌅ [fce5fe82] Turing v0.32.3
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0

Noting that we are blocked at v0.32.3 we should consider resolving the compat issue here and move to Turing 0.33. My sense is that Turing is improving quite fast at the moment and therefore it might make sense to devote some effort to maintaining compat with the latest version. 

For example, the new mode estimation API https://turinglang.org/docs/tutorials/docs-17-mode-estimation/ is not available with our version of Turing.

**Comment by seabbs** [comment]
So I think this brings up a broader issue in that we want our compact ot be minimum versions and not specific versions (as otherwise these need to be rolling updated by us which seems weird). What is standard Julia practice here? If the normal process is to have fixed compats then it seems like a scheduled action not test updated package versions would be a good idea

**Comment by SamuelBrand1** [comment]
Unfortunately, I'm not really sure what SOP is here in Juliaworld.

In the TuringLang ecosystem they use [CompatHelper.jl](https://github.com/JuliaRegistries/CompatHelper.jl) 

> CompatHelper is a Julia package that helps you keep your [compat] entries up-to-date. Whenever one of your package's dependencies releases a new breaking version, CompatHelper opens a pull request on your repository that modifies your [compat] entry to reflect the newly released version. We would like to eventually add Julia support to [Dependabot](https://dependabot.com/).

**Comment by SamuelBrand1** [comment]
CompatHelper is a rolling fixed compat helper so maybe preferable to `>=` type compat?

**Comment by seabbs** [comment]
I think ours is broken

**Comment by SamuelBrand1** [comment]
This might be due to other compat making it unsatisfiable which we should look at.

**Comment by seabbs** [comment]
Nah it is just broke! https://github.com/CDCgov/Rt-without-renewal/actions/runs/10404917186/job/28814468332

**Comment by seabbs** [comment]
See #426. I hotfixed our compat helper action. Something we need to decide is if we want to add new versions or drop old and replace. Its unclear to me how people are testing old package versions to make sure that they don't accidentally introduce functionality that depends on a more recent package version and so break their package on an old version.

**Comment by seabbs** [comment]
In the action output I see a few errors which are I think due to base packages. It isn't clear to me how to handle that either.

**Comment by SamuelBrand1** [comment]
Some context for this issue. At the moment `Pathfinder` 0.8/0.9-DEV is not compatible with `Turing` 0.33, which blocks updating to 0.33 for this project. But it looks like this is being addressed:

https://github.com/mlcolab/Pathfinder.jl/pull/189
https://github.com/TuringLang/Turing.jl/issues/2268

**Comment by SamuelBrand1** [comment]
Pathfinder 0.9 seems to fix the above.
