### ISSUE TITLE
Forecast function in pipeline is broken after move to daily increments of latent procs

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#433]

**Comment by seabbs** [comment]
noting there isn't enough detail here to interact with this issue (i.e this numerical instability - so the issue is numerical stability!)

**Comment by SamuelBrand1** [comment]
Changed title to better track current understanding of issue.

**Comment by SamuelBrand1** [comment]
This was closed by #478 - when we get `InexactError` due to very large numbers leading to a switch to `BigInt` then this is recorded without erroring.
