### ISSUE TITLE
CompatHelper doesn't trigger CI 

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#450]
It looks like `CompatHelper.jl` is currently broken (https://github.com/JuliaRegistries/CompatHelper.jl/issues/500) and so can't trigger CI for PRs. The suggested work around is to close and reopen. 

I am not clear if there is likely to be a fix anytime soon. Instead we could move to `renovate` (https://www.youtube.com/watch?v=Zj6tNebo93k&t=944s)

**Comment by SamuelBrand1** [comment]
> I am not clear if there is likely to be a fix anytime soon.

Thats disappointing, this a pretty widely used package.

**Comment by seabbs** [comment]
yes it is disappointing

**Comment by SamuelBrand1** [comment]
Is this working now?

**Comment by seabbs** [comment]
I don't know. Have you tested it?

**Comment by SamuelBrand1** [comment]
I think https://github.com/JuliaRegistries/CompatHelper.jl/pull/505 has fixed this?

**Comment by seabbs** [comment]
Nice! Are we pulling the right version? My impression from reading that is that if we have it properly configured this should now just work? I went through and setup the SSH previously (and hit this bug) so I think everything should be in place?

**Comment by SamuelBrand1** [comment]
This does seem to be working, e.g. #516 ?
