### ISSUE TITLE
New EpiAware infection generating process: generate from `SciML.solve`

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#465]
wow what if this was rewritten as an infection EpiAware infection model (new issue/PR)

_Originally posted by @seabbs in https://github.com/CDCgov/Rt-without-renewal/pull/464#discussion_r1784631345_
            
The idea here is to make a new infection generating model which ingests some `DEProblem` and generates the infections from `solve` on this object.

**Comment by seabbs** [comment]
Potentially this needs to wait for refactoring the infection submodule but also potentially could be done with it as it is and then have a later refactor
