### ISSUE TITLE
Investigate adding rectifier transformations to improve stability in sampling

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#467]
> Pertinent to above and @seabbs comment on using `upjitter`. Using the softplus transform instead of an upjitter (or clamp to do relu) stabilises the sampling. Also, using `LogExpFunctions.xexpy` to implement the effect of the AR process on observations in the stochastic model.
After these changes, an experiment to not use initial values to start NUTS still converges onto the correct posterior distributions, so at least in this context this is a big improvement in the stability of the model. I know @damonbayer has wrangled with this in Bayesian inference of ODEs so I wonder what your thoughts on using special functions to stabilise sampling are? 

_Originally posted by @SamuelBrand1 in https://github.com/CDCgov/Rt-without-renewal/issues/464#issuecomment-2391056217_
            
This finding really makes me wonder if we should have some kind of (preferable smooth) rectifier transformation as default in a large chunk of the modelling. Maybe via `TransformLatentModel` etc?

- [x] #471
- [x] New `Transform` struct as discussed https://github.com/CDCgov/Rt-without-renewal/issues/471#issuecomment-2396513414
- [x] #479
- [x] #469

**Comment by seabbs** [comment]
step one is being able to do all the transforms we have in the new vignette using `Transform` right?

**Comment by SamuelBrand1** [comment]
Final sub task of this was closed by #496
