### ISSUE TITLE
Check, and if possible apply, `Transform...` struct using softplus etc for chatzilena et al replication.

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#471]

**Comment by SamuelBrand1** [comment]
The tricky thing about this is that one of the transformations _combines_ the infection time series with the latent process e.g.

```julia
λt = xexpy.(log1pexp.(N * sol[2, :]), κₜ)
```

**Comment by SamuelBrand1** [comment]
Another thing is that we don't have a `Transform` for processes that aren't `AbstractLatentModel` subtypes. This is mainly because we are aiming to refactor infection processes as per #385 (I think).

This is an easy change though, which should make `Transform...` easy to include in any refactor.

**Comment by seabbs** [comment]
So is this in some sense a ascertainment model?

**Comment by SamuelBrand1** [comment]
Its more a question of _if_ we use this on things like the output of an ODE solve then do we want `Transform` to exist as a rectifier for that. The other option being that it lives "inside" the struct defining the ODE solve behaviour.

I think we do want a Transform struct modifier here because different choices have a big impact on inference (potentially) without changing anything else about the model.

**Comment by seabbs** [comment]
without being very clever if we then combined this with a Deterministic `TransformObsModel` (i.e like https://github.com/CDCgov/Rt-without-renewal/blob/main/EpiAware/src/EpiLatentModels/modifiers/TransformLatentModel.jl but on expected cases vs on a latent model) the we could express this in our current framework

**Comment by seabbs** [comment]
Also checking we do still have a hard coded pad: https://github.com/CDCgov/Rt-without-renewal/blob/0414f5f9da803950042e54ecf5032d67c43fd434/EpiAware/src/EpiObsModels/ObservationErrorModels/methods.jl#L21

**Comment by SamuelBrand1** [comment]
> Also checking we do still have a hard coded pad:
> 
> https://github.com/CDCgov/Rt-without-renewal/blob/0414f5f9da803950042e54ecf5032d67c43fd434/EpiAware/src/EpiObsModels/ObservationErrorModels/methods.jl#L21

I think not.

**Comment by seabbs** [comment]
thats literally a link to it?

**Comment by SamuelBrand1** [comment]
> without being very clever if we then combined this with a Deterministic `TransformObsModel` (i.e like https://github.com/CDCgov/Rt-without-renewal/blob/main/EpiAware/src/EpiLatentModels/modifiers/TransformLatentModel.jl but on expected cases vs on a latent model) the we could express this in our current framework

Agree. I started a bit of work on something like this inspired by example above. Only thing that seemed to need care was making sure that the struct that takes in some model and transformed it is itself the type we want.

For example, at the moment `TransformLatentModel` is an `AbstractLatentModel` therefore, `generate_latent` functions dispatch as expected. Whereas, making a `TransformModel` struct in the same way naively doesn't work correctly.

**Comment by SamuelBrand1** [comment]
> thats literally a link to it?

Ah I misread as "Do we _need_ a hard coded pad"

**Comment by seabbs** [comment]
> For example, at the moment TransformLatentModel is an AbstractLatentModel 

If we follow the prefix pattern then can do this using a utils function and a struct wrapper for each specific type. As these methods aren't quite the same though I think its basically just write a similar but not the same specific version for abstractobsmodel
