### ISSUE TITLE
Helpful Aliases for structs

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#501]
Yes we could and I agree that would be good for another issue (i.e add alieas for example making `AutoRegressive` exist and `AR`, `RandomWalk` and `RW` but the key issue we have here is making sure we have a standard and following it. 

Thee big thing that stands out to me is the the module is called `EpiObsModels` and we have `RecordExpectedObs` but everything else uses `Observations`

_Originally posted by @seabbs in https://github.com/CDCgov/Rt-without-renewal/issues/499#issuecomment-2407110193_
            
This issue is about choosing helpful aliases for common `struct` names. From my point of view, we want the most natural thing for the largest number of people to "just work".

**Comment by seabbs** [comment]
Close in favour of #499
