### ISSUE TITLE
Inclusion of day of week observation processes

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#51]
Should we include some simple day of week periodicity in order to better reflect real data in both the simulated scenarios and in the inference models (i.e. in the observation process). This issue is based on #34 

## Advantages

- Potentially better reflects real-world data
- Similarly, potentially better reflects real-world practice
- Will likely improve the performance of all models on real-world data

## Disadvantages

- We will need to choose what periodicity to simulate
- We will need to choose a modelling approach for inference (ideally from common practice - but there are still a few options to pick from).
- Make our simulated data more complex and so perhaps harder to cleanly visualise etc

## My thoughts

Overall the advantages outweigh the negatives so long as we pick something simple for the simulated data (a single scenario) and also stick with a simple method for interence. @SamuelBrand1 @zsusswein what do you both think?

**Comment by SamuelBrand1** [comment]
I think this seems ok! 

We could keep this simple by just having a simple weekend/not weekend effect. 

The easiest thing to do here is have a new observation_process object.

**Comment by seabbs** [comment]
>  The easiest thing to do here is have a new observation_process object.

Could we be trendy and compose on top of our current one (i.e multi-level nesting). }

What do you think @zsusswein? Too much complexity?

**Comment by seabbs** [comment]
How should we do this? As part of the observation submodel as it own submodel or make the observation model a composed submodel itself with a few default options set up by us?

**Comment by seabbs** [comment]
Any more thoughts on this @SamuelBrand1?

**Comment by SamuelBrand1** [comment]
This is connected to a wider issue of meta-data with case data, e.g. day_of_week. In general, a nice feature of the model is that it will generate/infer on data agnostically (its all random variables). Case meta-data is outside that paradigm, and we'd probably want to use `TuringGLM` rather than rolling our own capabilities.

Is the argument on this issue that we have periodicity as a special case in the observation model?

**Comment by seabbs** [comment]
> Is the argument on this issue that we have periodicity as a special case in the observation model?

Yes. I think depending on `TuringGLM` is a good idea but a whole additional load of complexity so in the first instance we should implement what we need and hold the door open to the more general solution

**Comment by seabbs** [comment]
With #80 we can start to revisit this.

I think there are two approaches: 

- Build this as part of the hierarchical support. This could look like implementing some kind of custom GLM wrapper
- Build this as a latent process model that can be modularly composed. We would then need an approach to make this composable within the observation model. Thinking about this as a kind of ascertainment could be a good abstraction for this. 
- Build this directly as a composable observation model. 

I think I favour the latent process approach. This would look like. 

```julia
struct ascertainment <: abstractobservationmodel
	abstractobservationmodel
    abstractlatentmodel
    link::function
end

struct DayofWeek <: abstractlatentproceess
	abstractlatentmodel
    priors
end

function generate_observations(ascertainment, y_t, Y_t)
	@submodel mod_Y_t, ... generate_latent(ascertainment.latentmodel, length(Y_t))

   exp_Y_t = Y_t .* ascertainment.link(mod_Y_t)

   @submodel ... generate_observations(ascertainment.observationmodel, y_t, exp_Y_t)

end
```

**Comment by seabbs** [comment]
We have all the tools to do this but we now need to stick them together to make this easy to hence reopening.

**Comment by seabbs** [comment]
Now that #203 is merged we have all the tools to do this apart from a link. Is the most sensible option here hand rolling a softmax? 

Following on from the broadcasting approach and based on f2f discussions I think we should make this a helper function in the `ascertainment_` family (so `ascertainment_dayofweek`)

**Comment by SamuelBrand1** [comment]
> Now that #203 is merged we have all the tools to do this apart from a link. Is the most sensible option here hand rolling a softmax?

Or make `LogExpFunctions` a dep; they have a bit of voodoo for edge cases.
