### ISSUE TITLE
Flesh out multiple simulated scenarios vs one long one

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#52]
Based on discussion in #34 we need to flesh out that our approach will use multiple simulated scenarios vs one long one because of potential issues at different absolute incidence levels and as it will be easier to communicate.

**Comment by seabbs** [comment]
@zsusswein I think you had precise thoughts on this. Any chance you have them noted down?

**Comment by seabbs** [comment]
Flagging this is still stuck waiting on notes from @zsusswein

**Comment by SamuelBrand1** [comment]
Bump @zsusswein

**Comment by zsusswein** [comment]
This has become a bit fuzzy with time, but I remember some of the following:

- We want to put the different modeling approaches through their paces with a few scenarios. These may include a step change in Rt, constant-ish Rt, sinusoidal structure, other stuff. The exact details of these aren't important for this particular discussion.
- I had originally pitched these different cases as components of one long composite timeseries. I thought (and still think!) it would simplify visualization and presentation a bit. I also generally like the idea of forcing a single model fit to contend with different orders of magnitude of incidence as a "more strenuous" test -- sort of along the lines of bumping true $R_t$ to the high end of a plausible range to make bias more obvious.
- But @seabbs pointed out the models are non-adaptive and we'd likely face some serious (and largely incidental to our question) model fitting issues. I think that's a fairly convincing argument and evaluation should be on multiple shorter timeseries each of which is an interesting test in some way.

**Comment by seabbs** [comment]
@SamuelBrand1 this is the issue were just looking for. Current plan is to look across 4 scenarios (2 outbreak and 2 endemic) with varying levels of complexity.
