### ISSUE TITLE
Create NullLatentModel

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#529]
> I think I've nearly fully addressed this concern. Where we might be missing something is not having a NullLatentModel type which just generates nothing values. I wanted to leave the option open for the ODE models to be conditional on a latent process outcome, e.g. as per a Renewal model, but that is not currently used. A nothing returning process would let us use the current infra for model specification.

Good idea

_Originally posted by @seabbs in https://github.com/CDCgov/Rt-without-renewal/issues/510#issuecomment-2468572438_
            
As discussed here, this would be an easy and handy feature.

**Comment by SamuelBrand1** [comment]
It also makes resolving #526 smoother, because we can reuse the `EpiProblem` pattern.

**Comment by seabbs** [comment]
Yes good point
