### ISSUE TITLE
AR(1) latent process

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#53]
As part of #3 we need an AR(1) process to be implemented. Ideally, this would also be general enough to support differencing and potentially AR(p) processes. 

Potential inspiration (doesn't look possible to depend directly?): 

- https://github.com/LAMPSPUC/StateSpaceModels.jl/blob/master/src/models/sarima.jl

**Comment by SamuelBrand1** [comment]
Thinking about how to specify this mathematically:

`n` differenced AR(p) process:

```math
\Delta^{(n)} X_t = \sum_{k = 1}^p \varphi_k X_{t-k}
```

**Comment by SamuelBrand1** [comment]
Hows this going?

**Comment by seabbs** [comment]
All good just being slow. Should have a PR today.
