### ISSUE TITLE
Abstraction for `init` value

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#64]
## Current API

For each latent process, an `init` scalar value is generated along with the latent process itself. The interpretation of `init` is typically $\log I(0)$; that is the log-incidence rate on the time step _before_ data.

## Problem

Although this API "works"; it locks in the interpretation above and makes iteration to other models that _might_ want more structured initialisation difficult.

## Solution

Create an initializer sub-model to be combined with latent processes and observation models.

**Comment by SamuelBrand1** [comment]
## Alternate solution

In `epidemia`, the inference priors for initialisation "live" with the [`epiinfs`](https://imperialcollegelondon.github.io/epidemia/reference/epiinf.html) model. At the moment we use `EpiModel` objects to transform latent process to latent infections; which corresponds to the `epiinfs` epidemia model when we choose `Renewal`.

Therefore, it would seem to be natural to add initialisation of latent infections to this struct.

**Comment by seabbs** [comment]
Hmm yes I think I agree with the alternative solution here? That does introduce a problem with priors maybe (as back to a shared prior list?)

**Comment by SamuelBrand1** [comment]
Btw, in comparison to `epidemia`.

- `LatentProcess` <-> `epirt`
- `ObservationModel` <-> `epiobs`
- `<: AbstractEpiModel` <-> `epiinf`

Main difference is that the subtype of `<: AbstractEpiModel` dispatches the target of the latent process.

**Comment by seabbs** [comment]
> Because we have three different concrete subtypes of AbstractEpiModel but we don't need that for LatentProcess.

I guess my question is why aren't we using a struct with a dict and function pairing vs this. 

Doing some reading (the manual and https://stackoverflow.com/questions/60218078/why-create-an-abstract-super-type-in-julia) it looks like abstract structs are all about inheritance and grouping of related objects. 

So here we are making some kind of contract that `AbstractEpiModel` will always use `EpiData` (except my read of the docs is that we are not doing this at the moment) and we could extend this to have a default (empty function) that can then be overloaded in inheriting structs? 

So my question is this seems like a useful way to do things so why don't we want the same for `LatentProcess` (i.e. `RandomWalkLatentProcess` etc.)? Or not need it for either (as we currently aren't doing any inheritance using out abstract struct?

**Comment by SamuelBrand1** [comment]
> So here we are making some kind of contract that `AbstractEpiModel` will always use `EpiData` (except my read of the docs is that we are not doing this at the moment) and we could extend this to have a default (empty function) that can then be overloaded in inheriting structs?

At the moment, we're implementing the latent process -> latent infections function (which defines the target of the inference) using a callable on the `<:AbstractEpiModel` struct, e.g.

https://github.com/CDCgov/Rt-without-renewal/blob/6fd0d380dfb424308cd8cadaf3768177bf1a7cc8/EpiAware/src/epimodel.jl#L77-L92

Which does use `EpiData` information, and the concrete type. This isn't the only or even best way to implement this pattern? I'm influenced by the pattern in `LogDensityProblems` here.

> So my question is this seems like a useful way to do things so why don't we want the same for `LatentProcess` (i.e. `RandomWalkLatentProcess` etc.)? Or not need it for either (as we currently aren't doing any inheritance using out abstract struct?

At the moment we aren't doing any inheritance for the `LatentProcess`; its implementation is down to the `Turing` model constructor passed to it (the `latent_process` field). To tell the truth, this was the due to me not being sure how inheritance would work since the `Turing` model constructor functions are themselves generated by the `@model` macro at compilation time for `EpiAware`.

As the example, you found suggested the abstract super-type pattern is particularly useful if there is a default behaviour we'd want from the latent process that we might specialise on with concrete sub-types. In this case, I can't think of one but I'm open to suggestions.

**Comment by seabbs** [comment]
?  In this case, I can't think of one but I'm open to suggestions.

What about for the args splitting?
