### ISSUE TITLE
Better double censoring approach to discretising continuous distributions

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#7]
The appropriate way to discretise a continuous distribution's pdf into a probability vector is still a somewhat open question.

Our default was the approach at [epinowcast](https://package.epinowcast.org/articles/distributions.html), however, it would be preferable to go to the more recent solution implemented [here](https://github.com/epinowcast/epinowcast/blob/3b2e94f269690dbbc4d1170db0aafffdb025253b/R/model-module-helpers.R#L293).

This can be directly translated into Julia.

**Comment by seabbs** [comment]
> The appropriate way to discretise a continuous distribution's pdf into a probability vector is still a somewhat open question.

I'm not sure this is true based on https://www.medrxiv.org/content/10.1101/2024.01.12.24301247v1 its more that most of the current implementations of the theory have issues that have yet to be corrected or those corrections have yet to make it into releases.

That being said above point doesn't impact the work proposed here.

**Comment by SamuelBrand1** [comment]
I would say 

> current implementations of the theory have issues that have yet to be corrected or those corrections have yet to make it into releases.

== appropriate way is still an open Q

**Comment by SamuelBrand1** [comment]
Question for @seabbs @zsusswein 

Given that we have some distributions where the delay after censoring can be `0` (e.g. primary and secondary events occur on same day), do you want arrays that index on `[0]`  using [OffsetArrays](https://github.com/JuliaArrays/OffsetArrays.jl)?

It doesn't hurt anything code wise and might avoid some gotchas when indexing?

**Comment by seabbs** [comment]
Hmm I see the interpretability benefit but in my head, I am now very much conditioned to think about up to day 1 now!

I would be happy to stick with the simple option of having to fudge the indexes a bit but I don't feel that strongly

**Comment by SamuelBrand1** [comment]
Closed by #10

**Comment by seabbs** [comment]
In the futuree if you say something like close #issue-number it will auto close the related issue when its merged in
