### ISSUE TITLE
Refactor to promote greater use of multiple dispatch and one paradigm programming

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#75]
## Problem

In the code base as it exists there is a mix of coding paradigms; for example `<: AbstractEpiModel` objects implement latent process to latent infection functions as callables on their type; but otoh, a single `LatentProcess` type struct contains the latent process as a struct function.

This makes the codebase confusing and harder to extend, as well as violating the design principles of the Julia language.

## Solution

Move to a design principle where each part of the model has its _behaviour_ determined by a dispatch on a type and its _implementation_ determined by a method being dispatched upon.

**Comment by seabbs** [comment]
Sounds good. Note this was motivated by a f2f discussion and agreed.

Once deciding issue is if methods that dispatch on a specific struct/dict should dispatch down to another method has the specific required arguments. 

This would meet my design goal of making all functions that aren't wrappers explicitly list their arguments (due to ease of testing, preventing potential bugs, and ease of documentation) but could be clunky and not required given that documentation etc could happen in the paired dict/struct. it also isn't clear to me that it would make sense to dispatch on the same type twice (with and without arguments). However this could open up a workflow where a struct partially contains a functions arguments with the rest passed when initialised (its not clear to me you would actually want this at all).

**Comment by seabbs** [comment]
Note @SamuelBrand1 is working on this in https://github.com/CDCgov/Rt-without-renewal/tree/refactor-for-more-multi-dispatch

**Comment by dylanhmorris** [comment]
> But could be clunky and not required given that documentation etc could happen in the paired dict/struct.

Isn't part of the appeal of type-determined function dispatch [^1] that it's reasonable for a function to "know" about the mandatory attributes of a/the struct(s) it gets passed? 

So this kind of Python should be avoided:

```python
def dist_from_origin(xy_coords: dict):
    return math.sqrt(xy_coords["x"] ** 2 + xy_coords["y"] ** 2)
```

Whereas this Julia seems fine to me:

```Julia
struct XYCoords
    x::Float32
    y::Float32
end

function dist_from_origin(xy_coords::XYCoords)
    return sqrt(xy_coords.x^2 + xy_coords.y^2)
end
```

Am I missing something?

[^1]: Multiple nor not

**Comment by SamuelBrand1** [comment]
@dylanhmorris Absolutely, the refactor is to do more of this!

The other possible benefit is separating behaviour from implementation.

So to extend your example:

```julia
#Parametric type of XYCoords
struct XYCoords{T}
    x::T
    y::T
end

#Catchall method
function dist_from_origin(xy_coords::XYCoords)
    @info "Weird choice of type here!"
    return nothing
end

#L2 norm for floats
function dist_from_origin(xy_coords::XYCoords{T}) where T<:AbstractFloat
    return sqrt(xy_coords.x^2 + xy_coords.y^2)
end

#Manhatten norm for integers
function dist_from_origin(xy_coords::XYCoords{T}) where T<:Integer
    return abs(xy_coords.x) + abs(xy_coords.y)
end

coord_string = XYCoords("A","B")
coord_double = XYCoords(1.5,1.5)
coord_float = XYCoords(1.5f0,1.5f0)
coord_int = XYCoords(2,1)
coord_wrong = XYCoords(2.5,1) # MethodError: no method matching XYCoords(::Float64, ::Int64)

dist_from_origin(coord_string) # nothing gives `[ Info: Weird choice of type here!` in REPL
dist_from_origin(coord_double) # 2.1213203435596424
dist_from_origin(coord_float) # 2.1213202f0, NB: type-stable
dist_from_origin(coord_int) # 3

```

**Comment by seabbs** [comment]
I had a look into dispatching on structs or dists in julia and.. 

> For Structs: Define a struct with the required fields. Julia's type system ensures the function is called with an argument of the correct structure.
> For Dicts: Perform runtime checks within the function to assert the presence and types of required keys. Unlike structs, dictionaries don't provide compile-time guarantees about their structure.

It looks like if your input is a struct then you are guarantee type and field checking for all required parts of it which mollifies some of my concerns about inputs (though not the doc or readability ones).

**Comment by dylanhmorris** [comment]
Yes, a dict seems like the wrong choice here, as in the Python anti-example.

RE: docs/readability, I'd aim to ensure (1) the struct itself is well-documented and (2) its fields have meaning names. In addition, presumably the function docs can and should link to the input struct docs?

**Comment by SamuelBrand1** [comment]
Its a pretty standard pattern to pass structs and dispatch on type information in Julia Packages.

For example, in `DifferentialEquations.jl` a workflow might be:

1. create a `DEProblem` struct (with different behaviours being `ODEProblem`, `SDEProblem` etc.
2. Choose a solution method struct, e.g. `Tsit5`
3. pass the above to `solve` e.g. `solve(prob; Tsit5())` along with any other key words.
