### ISSUE TITLE
Consider renaming DelayObservations and family

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#80]
As the title. This is currently hard coded to a negative binomial. We don't plan to change this out in our code but it would be nice to make it clear that we could if we wanted to and to make that process fairly straightforward. 

Options I see here are 1. A single name change or 2. A more complete update to either split delays from the obs model or introduce some further nesting.

https://github.com/CDCgov/Rt-without-renewal/blob/8b9edf95ae8a513f5af2f555b4895078122e5304/EpiAware/src/observation-processes.jl#L7

@SamuelBrand1 in particular thoughts on which of these to consider?

**Comment by SamuelBrand1** [comment]
Agreed and connected to #29

**Comment by SamuelBrand1** [comment]
e.g.

```julia
function DelayObservations(delay_dist; D_obs, sampling_dist = :negbin, dt = 1.0)
@assert sampling_dist is one of our two options
...double c discretisation...
K = make_observation_kernel(...)
if sampling_dist== :negbin
   ...
   return DelayObservation(...)
else
  ...
  return DelayObservationPoisson(...)

end
```

**Comment by SamuelBrand1** [comment]
Its surprisingly fiddly swapping between the two IMO due to going from one param to two param families. 

I think meta-maths reason because Poisson is an exponential family distribution and Neg bin is only when $r$ parameter is fixed (e.g. a one parameter family version of Neg Bin).

**Comment by seabbs** [comment]
I don't really love the above suggestion to be honest - it doesn't seem to fit the composability spirit.

We currently have two components in the delay observation model. The delay and the observation model. Can we decompose this further and so get around this issue?

**Comment by SamuelBrand1** [comment]
Yes, that could work.

What we'd want from the `Delay` bit of the model is something that maps latent infections into _expected_ observations. I think for 99% of use-cases this can just implemented by a (deterministic) function; but this could be random. For example, if actually modelling discrete infections the delay might be multinomial sampling on a delay distribution for each individual infection.

The implementation of `Observation` bit is then easy; it always expects a time series of averages and depending on the exact model it might have dispersion parameters to sample etc. In the discrete numbered infections above the `Observation` implementation would just be the identity map; the "expected" observations are the actual observations.

**Comment by seabbs** [comment]
Yes agree. I'll have a go at this and ping you for review in a bit

**Comment by seabbs** [comment]
Thinking more about this how does #51 fit into this pattern. It could either be considered a reporting process and so deserve its own submodel or be nested in one of the other models (likely the Observation submodel). 

I think I favour having the following submodels for the observation process: 

- `LatentDelayModel` (implying unobserved)
- `ReportingModel` (i.e day of week effects, hazards etc)
- `ObservationModel` (the actual observation model).

**Comment by seabbs** [comment]
This is blocked whilst we think about how to pass around the overall meta-model (which currently lacks an issue).

**Comment by seabbs** [comment]
We now have the meta model thinking (in #119 and #122) but maybe don't have clarity on this issue. 

Maybe its as simple as renaming what we have to `DelayNegativeBinomial` and making it very functionally modular internally + documenting (or even implementing) another observation model flavour?
