### ISSUE TITLE
Rename Abstract**Process to Abstract**Model for consistency?

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#88]
As the title

**Comment by SamuelBrand1** [comment]
Actually I was wondering about this process vs model naming business... Whats our naming decision?

**Comment by seabbs** [comment]
I think we don't have one but we should standardise. I'm open to either

**Comment by seabbs** [comment]
yes both good posts. updating the title. I thought I would tackle this along with #86

**Comment by seabbs** [comment]
Do we think this extends to all uses of process? For example `generate_latent_process`?

**Comment by seabbs** [comment]
I'm thinking yes

**Comment by SamuelBrand1** [comment]
I think yes, we might as well be consistent and make it like the user doesn't need to guess (whilst still being readable)
