### ISSUE TITLE
Either test `EpiAware` on Julia 1.9 or update `[compat]`

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#91]
As title.

Atm, the Project file `[compat]` requirement for julia is [1.9+](https://github.com/CDCgov/Rt-without-renewal/blob/dbaad6b1a2203ec29049658191c4b8aa3549d617/EpiAware/Project.toml#L31).

I don't think we have tested on `1.9`; personally I would be ok with changing to `1.10`, but if we keep `1.9` (or even earlier) we should test.

**Comment by seabbs** [comment]
This inconsistency came from restricting the test grid here: https://github.com/CDCgov/Rt-without-renewal/blob/dbaad6b1a2203ec29049658191c4b8aa3549d617/.github/workflows/test-EpiAware.yaml#L19

I think we should resolve by adding 1.9 explicitly here as well as the latest release.
