### ISSUE TITLE
Documentation CI is not working

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/Rt-without-renewal#95]
Looking at the CI fail

> julia_cmd=( julia --color=yes --code-coverage --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()' )

Is erroring because the `path` should be to the `EpiAware` subdir.

**Comment by SamuelBrand1** [comment]
I think we want [this](https://github.com/julia-actions/julia-docdeploy?tab=readme-ov-file#customizing-installation-of-package-into-docs-environment)

**Comment by seabbs** [comment]
I think we don't need an issue for this as that feature is in a draft PR!
